#!/usr/bin/env perl
$| = 1;
use warnings;
use strict;

my $t1 = time;
while (1) {
    &print_elapsed_time( $t1, time );
    sleep 1;
}

sub print_elapsed_time {
    my ( $t1, $t2 ) = @_;
    my $seconds = $t2 - $t1;
    my $hours = $seconds / 3600;
    # Round number to 2 digits after decimal point
    printf("%.2f %.2f\r", $hours, &minutes_and_seconds);
#    print &minutes_and_seconds, "\n";
}

sub minutes_and_seconds {
    my ( $t1, $t2 ) = @_;
    my $seconds = $t2 - $t1;
    my $minutes = $seconds / 60;
    return $minutes;
}
