#!/usr/bin/env perl
$| = 1;
use warnings;
use strict;

my $t1 = time;
while (1) {
    &print_elapsed_time( $t1, time );
    sleep 1;
}

sub print_elapsed_time {
    my ( $t1, $t2 ) = @_;
    my $diff = $t2 - $t1;
    my $hours = $diff / 3660;
    # Round number to 2 digits after decimal point
    printf("%.2f\r", $hours);
}
